name: Publish to nuget

on:
  push:
    branches:
      - main
    paths:
      - src/version.props
      - .github/workflows/nuget.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish NuGet
        uses: alirezanet/publish-nuget@v3.0.3
        with:
          PROJECT_FILE_PATH: src/Likvido.Utilities/Likvido.Utilities.csproj
          VERSION_FILE_PATH: src/version.props
          PACKAGE_NAME: Likvido.Utilities
          VERSION_REGEX: <Version>(.*)<\/Version>
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}